apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-web-app  
  labels:
    app: internal-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: internal-web-app
  template:
    metadata:
      labels:
        app: internal-web-app
    spec:
      imagePullSecrets:
        - name: cybr-registry-key
      containers:
      - name: web-container
        image: registry.cybr.huydo.net/internal-web-app:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: internal-web-service
spec:
  type: NodePort
  selector:
    app: internal-web-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: internal-web-app-ir
  namespace: default 
spec:
  entryPoints:
    - web        # Port 80
    # - websecure  # If using https
  routes:
    - match: Host(`webapp01.k8s.huydo.net`)
      kind: Rule
      services:
        - name: internal-web-service
          port: 80
