apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-web-app  # Khớp với APP_NAME trong Jenkins
  labels:
    app: internal-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: internal-web-app
  template:
    metadata:
      labels:
        app: internal-web-app
    spec:
      imagePullSecrets:
        - name: cybr-registry-key
      containers:
      - name: web-container # Khớp với container name trong lệnh 'set image'
        image: registry.cybr.huydo.net/internal-web-app:latest
        ports:
        - containerPort: 80
        # Thêm readiness probe để Jenkins 'rollout status' chính xác hơn
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: internal-web-service
spec:
  type: NodePort
  selector:
    app: internal-web-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 # Đã sửa từ 31080 về 30080
